import Company from '@/components/Company'
import Footer from '@/components/Footer'
import Hero from '@/components/Hero'
import NavBar from '@/components/NavBar'
import NewsLater from '@/components/NewsLater'
import Pricing from '@/components/Pricing'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <NavBar />
   <Hero />
   <Company />
   <NewsLater />
   <Pricing />
   <Footer />
    </>
  )
}
